# Generated by Django 4.1.3 on 2022-12-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=190)),
                ('scan', models.BooleanField(default=False)),
                ('test', models.CharField(max_length=200)),
            ],
        ),
    ]
