# Generated by Django 4.1.3 on 2022-12-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='test',
        ),
    ]
