# Generated by Django 4.1.3 on 2022-12-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_table_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
